name: Price Drop Strategy Workflow

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: "0 5 * * 1-5"  # Schedule job to run at 10:30 AM IST (5:00 AM UTC) on weekdays

jobs:
  run-price-drop:
    runs-on: ubuntu-latest  # GitHub-hosted runner for Linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Use the access token directly from GitHub Secrets
      - name: Set Access Token from GitHub Secrets
        run: echo "RUPEEZY_ACCESS_TOKEN=${{ secrets.RUPEEZY_ACCESS_TOKEN }}" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ap-south-1

      # Step 1: Run the eligibility check script before placing orders
      - name: Run Stock Eligibility and Price Check Script
        run: |
          python rupeezy/beest_eligibility_and_price_check.py

      # Step 2: Run the price drop strategy script
      - name: Run Price Drop Strategy Script
        run: |
          python rupeezy/price_drop.py
        env:
          RUPEEZY_API_KEY: ${{ secrets.RUPEEZY_API_KEY }}
          RUPEEZY_ACCESS_TOKEN: ${{ secrets.RUPEEZY_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1
          RUPEEZY_APPLICATION_ID: dev_3sK5DZDR

      # Step 3: Upload the order_ids.txt file as an artifact (enabled now)
      - name: Upload order_ids.txt as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: order_ids
          path: order_ids.txt
