name: Run Python Script

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest  # Ensure this uses GitHub-hosted runner for Linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Specifying version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Access Token Artifact
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Set GH_TOKEN for GitHub CLI authentication
        run: |
          gh run download --repo ${{ github.repository }} --name access_token --dir ./token

      - name: Check Artifact Directory
        run: |
          ls ./token

      - name: Set Access Token as Environment Variable
        run: |
          ACCESS_TOKEN=$(cat ./token/access_token.txt)
          echo "ACCESS_TOKEN=${ACCESS_TOKEN}" >> $GITHUB_ENV

      - name: Run Trading Script
        run: |
          python chartink_script_test_2.py
        env:
          YOUR_API_KEY: ${{ secrets.YOUR_API_KEY }}
          ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}
