name: Example Workflow

on:
  push:
    branches:
      - '*'  # Trigger on any branch
  pull_request:
    branches:
      - '*'  # Trigger on any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Script
        run: |
          python script.py
