name: Generate TOTP

on: [push]

jobs:
  generate_totp:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install pyotp

    - name: Generate TOTP
      run: |
        python -c "import pyotp; print(pyotp.TOTP('KUGBEDKB2BCGGRNKVJIP3Q64BQROAPO7').now())" > totp.txt

    - name: Display TOTP
      run: cat totp.txt
