name: Generate TOTP

on:
  workflow_dispatch: # Allows manual triggering of the workflow from the Actions tab

jobs:
  generate_totp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install pyotp

      - name: Generate TOTP
        id: generate_totp
        run: |
          python -c "import pyotp, os; print(pyotp.TOTP(os.getenv('TOTP_SECRET_KEY')).now())" > totp.txt
          echo "TOTP=$(cat totp.txt)" >> $GITHUB_ENV

      - name: Display TOTP
        run: |
          echo "Generated TOTP: ${{ env.TOTP }}"

      - name: Clean up
        run: |
          rm totp.txt
