name: Generate TOTP

on: [workflow_dispatch]

jobs:
  generate_totp:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install pyotp

      - name: Generate TOTP
        env:
          TOTP_SECRET_KEY: ${{ secrets.TOTP_SECRET_KEY }}
        run: |
          TOTP=$(python -c 'import pyotp, os; print(pyotp.TOTP(os.getenv("TOTP_SECRET_KEY")).now())')
          echo "Generated TOTP: $TOTP"
          echo "TOTP=$TOTP" >> $GITHUB_ENV

      - name: Trigger Login Workflow
        uses: actions/github-script@v4
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'login_with_totp.yml',
              ref: 'main',
              inputs: {
                totp: process.env.TOTP
              }
            })
