name: Login with TOTP

on:
  workflow_dispatch: # Allows manual triggering of the workflow from the Actions tab

jobs:
  login_with_totp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Login Script
        env:
          TOTP_SECRET_KEY: ${{ secrets.TOTP_SECRET_KEY }} # Set the environment variable for TOTP
        run: |
          python login.py
