name: Login with TOTP and Save Access Token

on:
  workflow_dispatch:
    inputs:
      totp:
        description: 'TOTP for Login'
        required: true

jobs:
  login_with_totp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Login Script
        env:
          TOTP: ${{ github.event.inputs.totp }}
          YOUR_API_KEY: ${{ secrets.YOUR_API_KEY }}
          YOUR_CLIENT_CODE: ${{ secrets.YOUR_CLIENT_CODE }}
          YOUR_PASSWORD: ${{ secrets.YOUR_PASSWORD }}
          YOUR_APPLICATION_ID: ${{ secrets.YOUR_APPLICATION_ID }}
        run: |
          ACCESS_TOKEN=$(python login.py)
          echo "$ACCESS_TOKEN" > access_token.txt

      - name: Fetch GitHub Public Key
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        id: fetch-key
        run: |
          gh auth login --with-token <<< "$PAT_TOKEN"
          gh repo secret set ACCESS_TOKEN --env=ACCESS_TOKEN_FILE --hidden --value-file access_token.txt

      - name: Verify Secret Update
        run: |
          gh repo secret list
