name: Test DynamoDB Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-dynamodb:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Install boto3 to interact with AWS services
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3

      # Set AWS credentials (Make sure to set these as GitHub Secrets)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Run the Python script to scan DynamoDB
      - name: Run DynamoDB Scan Script
        run: python test_dynamodb_scan.py
